In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import spinmob as sm
import mcphysics as mphys
from scipy.optimize import curve_fit

In [2]:
def Gaussian(x, m, o, C):
    return C*np.exp(-0.5*(((x-m)/o)**2))

def Linear(x, a, b):
    return a*x+b

def Data(angle, number, source):
    xData = mphys.data.load_chn('Cs-137 Calibration 000.chn')[0]
    databox = [None]*10
    i=0
    while i <= 9:
        databox[i] = mphys.data.load_chn('Compton/Angles/' + angle + '/' + number + ' Other Sources/' + source + 
                                         '/' + source + ' 00' + str(i) + '.Chn')[1]
        i += 1
    return [xData, np.average(databox, axis=0), np.std(databox, axis=0, ddof=1),
                    np.std(databox, axis=0, ddof=1)/np.sqrt(10)]

def Fit(input_databox, interval, guess):
    param, cov = curve_fit(Gaussian, input_databox[0][guess-interval:guess+interval], 
                           input_databox[1][guess-interval:guess+interval], p0=[guess, 10, 10])
    error = np.sqrt(np.diag(cov))
    print(param), print(error)
    return [param, error]

#plt.scatter(Data('220', '00', 'Cs-137')[0], Data('220', '00', 'Cs-137')[1], color='green')
#plt.scatter(Data('220', '04', 'Cs-137')[0], Data('220', '04', 'Cs-137')[1], color='blue')

Cs_220_00 = Fit(Data('220', '00', 'Cs-137'), 300, 1742)
Ba_220_00 = Fit(Data('220', '00', 'Ba-133'), 300, 850)
Co_220_00 = Fit(Data('220', '00', 'Co-57'), 300, 375)
Na_220_00 = Fit(Data('220', '00', 'Na-22'), 300, 1360)

firstCallibration = curve_fit(Linear, [Cs_220_00[0][0], Ba_220_00[0][0], Co_220_00[0][0], Na_220_00[0][0]], 
                              [662.1, 80, 122, 511.0], 
                              sigma = [Cs_220_00[1][0], Ba_220_00[1][0], Co_220_00[1][0], Na_220_00[1][0]])

plt.plot(xData, Linear(xData, *firstCallibration[0]))
plt.scatter([Cs_220_00[0][0], Ba_220_00[0][0], Co_220_00[0][0], Na_220_00[0][0]], [662.1, 80, 122, 1274])

[1754.01058028   60.77129231    8.11739977]
[0.67181609 0.6718161  0.07771525]
[924.23103882 132.62853427  16.63515431]
[3.97886748 4.2945523  0.42463696]
[ 356.33098779   18.41589656 1569.84045664]
[ 0.26477331  0.26477331 19.54572727]
[1370.87170884   54.68385266   17.99606295]
[0.59873027 0.59873027 0.17063644]


NameError: name 'xData' is not defined